[project]
name = "caso-muerte"
version = "0.1.0"
description = "Proyecto final reporte de muertes"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "pyarrow>=22.0.0",
    "scipy>=1.16.3",
    "streamlit>=1.50.0",
]
